# This script searches CSV_FILE_DIR (set in line 16) for csv files generated by
# eggnog-mapper (emapper) and formats them into an N x K matrix (N isolates, K KOs)
# where the ij-th element is the number of occurrences of KO j in isolate i. The emapper
# output files are csvs named isolate1.csv, isolate2.csv, ...
# The script compares the results to previous versions of the files (lines 79-107)
# if those files can be loaded.
# The resulting matrix is saved as file.path(CSV_FILE_DIR, "../../formatted", "isolate_ko_matrix.csv")

# load packages
library(dplyr)
library(stringr)
library(tibble)
library(tidyr)
library(data.table)

CSV_FILE_DIR <- "../data/kegg/ko_annotations/emapper_outputs" # directory containing annotation csv files
cat(sprintf("Reading EggNOG files from %s\n", CSV_FILE_DIR))

parse_single_file <- function(file_path) {
  # returns a tibble containing any KOs found in the  
  # file. KO is anything with ko:K* where * are digits
  
  file_lines <- readLines(file_path)
  
  ko_lines <- tail(file_lines, -4) # remove comment lines
  
  # parse anything with ko:K* where * are digits
  tibble(
    ko=str_extract_all(ko_lines, "ko:K\\d+")
  ) %>%
    unnest(ko) %>%
    mutate(ko=str_remove(ko, "ko:"))
}

# annotation files (one per isolate)
all_files <- list.files(CSV_FILE_DIR, full.names=TRUE)
isolate_annotation_files <- all_files[ grepl("eggnog\\.emapper\\.annotations\\.csv", basename(all_files)) ]
names(isolate_annotation_files) <- isolate_annotation_files %>%
  basename() %>%
  str_remove("\\.eggnog\\.emapper\\.annotations\\.csv")

# # load the annotations for 8 new Haemophilus influenzae genomes
# if(dir.exists(file.path(CSV_FILE_DIR, "new_haemophilus_isolates"))) {
#   h_inf_annotation_files <- list.files(file.path(CSV_FILE_DIR, "new_haemophilus_isolates"), full.names=TRUE)
#   h_inf_annotation_files <- h_inf_annotation_files[ grepl("eggnog\\.emapper\\.annotations", basename(h_inf_annotation_files)) ]
#   names(h_inf_annotation_files) <- h_inf_annotation_files %>%
#     basename() %>%
#     str_remove("eggnog\\.emapper\\.annotations") %>%
#     paste0("Haemophilus_influenzae_", .)
#   isolate_annotation_files <- c(isolate_annotation_files, h_inf_annotation_files)
# }

cat(sprintf("Loaded annotations for %d isolates\n", length(isolate_annotation_files)))

# parse annotations for each isolate
long_isolate_kos <- lapply(
  isolate_annotation_files,
  parse_single_file
) %>%
  rbindlist(idcol="isolate")

# to wide format
wide_isolate_kos <- long_isolate_kos %>% 
  group_by(isolate, ko) %>%
  tally() %>%
  pivot_wider(names_from=ko, values_from=n, values_fill=0)

# reorder columns
wide_isolate_kos <- wide_isolate_kos[,sort(colnames(wide_isolate_kos))] %>%
  ungroup()
cat(sprintf("matrix contains %d isolates and %d KOs\n",
            nrow(wide_isolate_kos),
            ncol(wide_isolate_kos)-1))

# load previous version - should be identical
prev_version_check_result <- tryCatch({
  
  # load previous version
  # fread has always generated an warning here due to a formatting error in the tsv file
  # this code fixes it
  prev_emapper <- fread(file.path(CSV_FILE_DIR, "../reference_files", "emapper_all.tsv")) %>%
      as.data.frame()
  prev_emapper_isolates <- prev_emapper$V1
  ko_names <- tail(colnames(prev_emapper), -2)
  prev_emapper <- prev_emapper[ ,2:(ncol(prev_emapper)-1) ]
  colnames(prev_emapper) <- ko_names
  rownames(prev_emapper) <- prev_emapper_isolates
  prev_emapper <- prev_emapper %>%
    rownames_to_column("isolate") %>%
    arrange(match(isolate, wide_isolate_kos$isolate)) %>%
    as_tibble()
  
  # only check against isolates/KOs present in old emapper
  wide_isolate_for_check <- wide_isolate_kos %>%
    filter(isolate %in% prev_emapper$isolate) %>%
    arrange(match(isolate, prev_emapper$isolate))
  wide_isolate_for_check <- wide_isolate_for_check[,colnames(prev_emapper)]
    
  # check result matches previous version
  identical(prev_emapper %>% as_tibble(), wide_isolate_for_check)
  }, error=function(e) {
    return(NULL)
  }
)

if(is.null(prev_version_check_result)) {
  warning("Failed to load previous emapper version (emapper_all.tsv) - not checking result", call.=FALSE)
} else if(!prev_version_check_result) {
  warning("New version does not match emapper_all.tsv!", call.=FALSE)
} else if(prev_version_check_result) {
  cat("Matrix matches old emapper\n")
}

# save final csv
cat(sprintf("Writing file to %s\n", file.path(CSV_FILE_DIR, "isolate_ko_matrix.csv")))
wide_isolate_kos %>%
  fwrite(file.path(CSV_FILE_DIR, "../../formatted", "isolate_ko_matrix.csv"))
cat("Script finished succesfully\n")
